<!-- {{define: curGame=bl}} -->
<!-- {{define: showRevert=1}} -->
<!-- {{import: commonHead}} -->
<!-- {{import: commonBody0}} -->
<!-- {{import: blRecommendBar}} -->
<!-- {{import: qnRecommendBar}} -->
<!-- {{import: jlRecommendBar}} -->
<!-- {{import: commonBody1}} -->
<!-- {{import: blMainSection}} -->
<!-- {{import: qnMainSection}} -->
<!-- {{import: jlMainSection}} -->
<!-- {{import: commonBody2}} -->
<!-- {{import: blScript}} -->
<!-- {{import: commonFooter}} -->