<!-- {{define: curGame=qn}} -->
<!-- {{define: showRevert=1}} -->
<!-- {{import: commonHead}} -->
<!-- {{import: commonBody0}} -->
<!-- {{import: qnRecommendBar}} -->
##<!-- {{import: jlRecommendBar}} -->
##<!-- {{import: blRecommendBar}} -->
<!-- {{import: commonBody1}} -->
<!-- {{import: qnMainSection}} -->
##<!-- {{import: jlMainSection}} -->
##<!-- {{import: blMainSection}} -->
<!-- {{import: commonBody2}} -->
<!-- {{import: qnScript}} -->
<!-- {{import: commonFooter}} -->